FROM eclipse-temurin:22.0.1_8-jre-jammy
WORKDIR /app
COPY target/projet9microserviceassessment-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "projet9microserviceassessment-0.0.1-SNAPSHOT.jar"]
EXPOSE 8084