services:

  microservice_patient:
    image: microservice_patient:1.0    
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/microservicePatient
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
          
  microservice_assessment:
    image: microservice_assessment:1.0    
    ports:
      - "8084:8084"      
    environment:
      - SPRING_PROFILES_ACTIVE=docker       
  
  microservice_note:
    image: microservice_note:1.0    
    ports:
      - "8083:8083"    
    environment:
      - SPRING_DATA_MONGODB_HOST=host.docker.internal
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin
      - SPRING_PROFILES_ACTIVE=docker
  
  microservice_front:
    image: microservice_front:1.0    
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  
  microservice_gateway:
    image: microservice_gateway:1.0    
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      