server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: routefront
          uri: http://host.docker.internal:8082
          predicates:
          - Path=/ui/**
        - id: patient
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/patient/**
        - id: notes
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/notes/**
        - id: assessment
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/assessment/**


