# application configuration
server.port: 8083
server.error.include-message: always

# mongodb configuration.
spring.data.mongodb.host: localhost
spring.data.mongodb.port: 27017
spring.data.mongodb.database: notes

